<?php
  $openUrl = $this->openUrl($this->driver, 'record');
  $openUrlActive = $openUrl->isActive();
  $doi = $this->doi($this->driver, 'record');
  $doiActive = $doi->isActive();
  // Account for replace_other_urls setting
  $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
?>
<?php foreach ($urls as $current): ?>
  <?php // AK: Translate the description ?>
  <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" target="_blank"><?=$this->transEsc($current['desc'])?></a><br/>
<?php endforeach; ?>
<?php if ($openUrlActive): ?>
  <?=$openUrl->renderTemplate()?><br/>
<?php endif; ?>
<?php if ($doiActive): ?><?=$doi->renderTemplate()?><?php endif; ?>
