<?php
  // Set up page title:
  $this->headTitle($this->translate('Checked Out Items'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';

  // Check if "Renew All" button can be displayed:
  $renewAll = !$this->ilsPaging || !$paginator;
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Checked Out Items')?></h2>
  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <?php if (!empty($this->transactions)): ?>
    <nav class="search-header hidden-print">
      <?php if ($paginator): ?>
        <div class="search-stats">
          <?php
            $end = min(
              $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage()),
              $paginator->getTotalItemCount()
            );
            $transParams = [
              '%%start%%' => $this->localizedNumber($paginator->getAbsoluteItemNumber(1)),
              '%%end%%' => $this->localizedNumber($end),
              '%%total%%' => $this->localizedNumber($paginator->getTotalItemCount())
            ];
          ?>
          <?=$this->translate('showing_items_of_html', $transParams); ?>
        </div>
      <?php endif; ?>
      <?php if ($this->sortList): ?>
        <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
      <?php endif; ?>
    </nav>
    <?php if ($this->renewForm): ?>
    <form name="renewals" method="post" id="renewals" data-clear-account-cache="checkedOut">
      <div class="toolbar">
        <div class="checkbox">
          <label>
            <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
            <?=$this->transEsc('select_page')?>
          </label>
          <input type="submit" class="btn btn-default" id="renewSelected" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
          <?php if ($renewAll): ?>
            <input type="submit" class="btn btn-default" id="renewAll" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
          <?php endif; ?>
        </div>
      </div>
    <?php endif; ?>

    <?php foreach ($hiddenTransactions as $ilsDetails): ?>
      <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
        <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
        <?php $prefix = $ilsDetails['title'] ?? $ilsDetails['item_id']; ?>
        <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
          <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
        <?php else: ?>
          <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><?php endif; ?></div>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
        <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
        <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
      <?php endif; ?>
    <?php endforeach; ?>

    <?php $i = 0; foreach ($this->transactions as $resource): ?>
      <hr>
      <?php // AK: Get source identifier ?>
      <?php $source = $resource->getSourceIdentifier(); ?>
      <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="result">
        <?php if ($this->renewForm): ?>
          <div class="checkbox">
            <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
              <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
              <label>
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
              </label>
              <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
              <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
            <?php else: ?>
              <label> </label>
            <?php endif; ?>
          </div>
        <?php endif; ?>

        <?php
          $coverDetails = $this->record($resource)->getCoverDetails('checkedout', 'small', $this->recordLink()->getUrl($resource));
          $cover = $coverDetails['html'];
          $thumbnail = false;
          $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
          if ($cover):
            ob_start(); ?>
            <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
              <?=$cover ?>
            </div>
            <?php $thumbnail = ob_get_contents(); ?>
          <?php ob_end_clean(); ?>
        <?php endif; ?>
        <div class="media">
          <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
            <?=$thumbnail ?>
          <?php endif ?>
          <div class="media-body">
            <?php
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                // AK: Getting whole title of resource
                $title = (is_a($resource, 'AkSearch\\RecordDriver\\SolrMarc')) ? $resource->getWholeTitle() : $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource) . '" class="title">' . $title . '</a>';
              } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>

            <?php // AK: Space between title (and parent data if applicable) and the rest of the data ?>
            <div class="spacer">
              <?php // AK: Show parent data. Replaces "Published in" from original VuFind code. ?>
              <?php foreach ($data = ($resource->getConsolidatedParents() ?? []) as $key => $value): ?>
                <?php // AK: Get some values about the parent if there is one
                  $pntVolNo = $value['volNo'] ?? null;
                  $pntTitle = $value['title'] ?? null;
                  $pntId    = $value['id'] ?? null;
                  $isDepLit = strpos(strtolower($resource->getFormat()), 'dependentliterature') === false ? false : true;
                ?>
                <?php if ($pntTitle): ?>
                  <span title="<?=((!$isDepLit && $pntVolNo) ? $this->transEsc('volume').' '.$this->escapeHtml($pntVolNo).' '.$this->transEsc('from') : $this->transEsc('In')) .': '.$this->escapeHtml($pntTitle)?>">
                    <?=((!$isDepLit && $pntVolNo) ? $this->transEsc('volume').' <i>'.$this->escapeHtml($pntVolNo).'</i> '.$this->transEsc('from') : $this->transEsc('In')).': '?>
                    <a href="<?=($pntId ? $this->recordLink()->getUrl("$source|$pntId") : $this->record($resource)->getLink('title', str_replace(['{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'], '', $pntTitle)))?>"><?=$this->highlight($pntTitle)?></a>
                  </span>
                  <br />
                <?php endif; ?>
              <?php endforeach; ?>
            </div>

            <?php // AK: Get all contributors ?>
            <?php $summAuthors = $resource->getContributors(); if (!empty($summAuthors)): ?>
              <span title="<?=implode('; ', $summAuthors)?>">
                <b><?=$this->transEsc('participants')?>:</b>
                <?php $authorCount = count($summAuthors); ?>
                <?php foreach ($summAuthors as $i => $summAuthor): ?>              
                  <a href="<?=$this->record($resource)->getLink('author', $this->highlight($summAuthor, null, true, false))?>"><?=$this->highlight($summAuthor)?></a><?=$i + 1 < $authorCount ? ';' : ''?>
                <?php endforeach; ?>
              </span>
              <br />
            <?php endif; ?>

            <?php // AK: Get publication dates ?>
            <?php if (!empty($pubYear = $ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Published')?>:</strong> <?=$this->escapeHtml($pubYear)?>
              <br />
            <?php elseif (!empty($pubYear = $resource->getPublicationDates())): ?>
              <strong><?=$this->transEsc('Published')?>:</strong> <?=$this->escapeHtml(implode('; ', $pubYear))?>
              <br />
            <?php endif; ?>

            <?php // AK: Get publishers ?>
            <?php if (!empty($publishers = $resource->getPublishers())): ?>
              <b><?=$this->transEsc('Publisher')?>:</b> <?=join('; ', $publishers)?>
              <br />
            <?php endif; ?>

            <?php if ($this->displayItemBarcode && !empty($ilsDetails['barcode'])): ?>
              <strong><?=$this->transEsc('Barcode')?>:</strong> <?=$this->escapeHtml($ilsDetails['barcode'])?>
              <br />
            <?php endif; ?>

            <?php // AK: Added links ?>
            <?php // We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
            // but even if we don't plan to display the link, we still want to get the $openUrl
            // value for use in generating a COinS (Z3988) tag -- see bottom of file.
            $openUrl = $this->openUrl($resource, 'results');
            $openUrlActive = $openUrl->isActive();
            $doi = $this->doi($resource, 'results');
            $doiActive = $doi->isActive();
            // Account for replace_other_urls setting
            $urls = $this->record($resource)->getLinkDetails($openUrlActive);
            if ($openUrlActive || $doiActive || !empty($urls)):
            ?>
              <?php if ($openUrlActive): ?>
                <br/>
                <?=$openUrl->renderTemplate()?>
              <?php endif;?>
              <?php if ($doiActive): ?>
                <br/>
                <?=$doi->renderTemplate()?>
              <?php endif; ?>
              <?php // AK: Custom URL display ?>
              <?php if (!is_array($urls)) $urls = []; if(!$resource->isCollection()): ?>
              <b><?=$this->transEsc('links')?>:</b>
              <?php $urlCount = count($urls); foreach ($urls as $i => $current): ?>
                <?php // TODO: AK: These are not only fulltext URLs! ?>
                <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext" target="new"><i class="fa fa-external-link" aria-hidden="true"></i> <?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></a><?=$i + 1 < $urlCount ? ';' : ''?>
                <?php endforeach; ?>
              <?php endif; ?>
            <?php endif; ?>

            <?php // AK: Added spacer ?>
            <div class="spacer">
              <?php if (count($resource->getFormats()) > 0): ?>
                <?=$this->record($resource)->getFormatList() ?>
                <br/>
              <?php endif; ?>
            </div>
            
            <?php // AK: Added spacer and alert-info box ?>
            <div class="alert alert-info spacer">
              <?php if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
                <strong><?=$this->transEsc('Library')?>:</strong> <?=$this->transEscWithPrefix('location_', $ilsDetails['institution_name'])?>
                <br />
              <?php endif; ?>

              <?php if (!empty($ilsDetails['borrowingLocation'])): ?>
                <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEscWithPrefix('location_', $ilsDetails['borrowingLocation'])?>
                <br />
              <?php endif; ?>

              <?php if (isset($ilsDetails['renew'])): ?>
                <strong><?=$this->transEsc('Renewed')?>:</strong> <?=$this->transEsc($ilsDetails['renew'])?>
                <?php if (isset($ilsDetails['renewLimit'])): ?>
                  <?=$this->transEsc($ilsDetails['renewLimit'])?>
                <?php endif; ?>
                <br />
              <?php endif; ?>
            
              <?php // AK: Separated renew messages in alert boxes and display of due date. Added fontawesome calendar icons in front of due date for emphasising it. ?>
              <?php $showStatus = true; ?>
              <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
                <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
                <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                  <?php $showStatus = false; ?>
                  <strong><i class="fa fa-calendar-check-o" aria-hidden="true"></i> <?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($renewDetails['new_date'])?> <?php if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><?php endif; ?></strong>
                <?php else: ?>
                  <strong><i class="fa fa-calendar-check-o" aria-hidden="true"></i> <?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?></strong>
                <?php endif; ?>
              <?php else: ?>
                <strong><i class="fa fa-calendar-check-o" aria-hidden="true"></i> <?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?></strong>
              <?php endif; ?>
            </div>

            <?php // AK: Separated renew messages in alert boxes and display of due date ?>
            <?php $showStatus = true; ?>
            <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
              <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
              <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <?php $showStatus = false; ?>
                <div class="alert alert-success"><?=$this->transEsc('renew_success')?></div>
              <?php else: ?>
                <div class="alert alert-danger"><?=$this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><?php endif; ?></div>
              <?php endif; ?>
            <?php else: ?>
              <?php if ($showStatus): ?>
                <?php if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
                  <div class="alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
                <?php elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
                  <div class="alert alert-warning"><?=$this->transEsc("renew_item_due")?></div>
                <?php endif; ?>
              <?php endif; ?>
            <?php endif; ?>

            <?php if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <?php endif; ?>
            <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
              <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
            <?php endif; ?>
          </div>

          <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
            <?=$thumbnail ?>
          <?php endif ?>
        </div>
        <?=$resource->tryMethod('supportsCoinsOpenUrl')?'<span class="Z3988" title="' . $this->escapeHtmlAttr($resource->getCoinsOpenUrl()) . '"></span>':''?>
      </div>
    <?php endforeach; ?>
    <hr>
    <?php if ($this->renewForm): ?></form><?php endif; ?>
    <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', compact('params')) : ''?>
  <?php else: ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'checkedout'])?>
</div>
