<?php
    // Set up page title:
    $this->headTitle($this->translate('about'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active"><a href="' . $this->url('content-page', ['page' => 'about']) . '">' . $this->transEsc('about') . '</a></li>';
?>

<div class="container">
    <h2>Über AKsearch / Impressum</h2><br />
    <p>
        <h3>Offenlegung</h3>
        <h4>Medieninhaber, Herausgeber und Eigentümer</h4>
        AK Bibliothek Wien für Sozialwissenschaften<br />
        Prinz-Eugen-Straße 20-22, 1040 Wien, Österreich<br />
        Telefon: <?=$this->escapeHtml($this->library_phone)?><br />
        eMail: <?=$this->escapeHtml($this->library_email)?><br />
        <br />
        <h4>Weitere Informationen</h4>
        Zuständige Aufsichtsbehörde: Bundesministerium für Arbeit, Familie und Jugend<br />
        Anwendbare Rechtsvorschriften: Bundesgesetz über die Kammern für Arbeiter
        und Angestellte und die Bundeskammer für Arbeiter und Angestellte
        (Arbeiterkammergesetz 1992 - AKG), BGBL 626/1991<br />
        Vertretungsbefugtes Organ: <?=$this->escapeHtml($this->representation_authority)?><br />‌
        <br />‌<br />
    </p>

    <p>
        <h3>VuFind</h3>
        <p>
            AKsearch ist eine für die AK Bibliothek Wien angepasste Version der
            Open-Source-Software <a href="https://vufind.org" target="_blank">VuFind
            </a> (https://vufind.org). Sie wird unter der Lizenz
            <a href="https://www.gnu.org/licenses/old-licenses/gpl-2.0.html"
            target="_blank">GNU General Public License v2.0</a>
            (https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) angeboten.
            Allen EntwicklerInnen und der gesamten VuFind-Community wollen wir an
            dieser Stelle einen besonderen Dank für ihre hervorragende Arbeit
            und ihr Engagement für eine freie und offene Software aussprechen.
        </p>
    </p>
    <p>
        <h3>Icons</h3>
        Untenstehende Icons werden in AKsearch verwendet. Überaus dankbar wurden
        sie vom <a href="https://thenounproject.com/" target="_blank">Noun Project
        </a> (https://thenounproject.com/) übernommen. Vielen Dank an all die
        kreativen Köpfe, die ihre Arbeit mit anderen teilen. Alle Icons stehen unter
        der <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank">
        Lizenz CC BY 3.0</a> (https://creativecommons.org/licenses/by/3.0/). Alle
        Icons wurden leicht verändert (hauptsächlich in Größe und Farbe).<br />
        <br />
        <ul>
            <li><a href="https://thenounproject.com/icon/70094/" target="new">article</a> by Dmitry Podluzny from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/108321/" target="new">audiobook</a> by Creative Stall from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/353763/" target="new">Book</a> by To Uyen from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/137857/" target="new">books</a> by Jakub Čaja from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/2301/" target="new">Braille</a> by Jakob Vogel from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/329990/" target="new">Clapperboard</a> by lastspark from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/166097/" target="new">Compact Disc</a> by Jamison Wieser from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/166092/" target="new">compact disk</a> by Jamison Wieser from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/166093/" target="new">DVD</a> by Jamison Wieser from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/253541/" target="new">ebook</a> by Vectors Market from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/16250/" target="new">Film</a> by José Campos from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/575708/" target="new">Headphones</a> by Kevin from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/102049/" target="new">Help Document</a> by Muneer A.Safiah from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/91481/" target="new">html</a> by Konstantin Velichko from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/11528/" target="new">Knight</a> by Christopher T. Howlett from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/75077/" target="new">magazine</a> by Glenis Gómez Rios from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/26944/" target="new">Map</a> by Juan Pablo Bravo from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/1565/" target="new">Media</a> by Thibault Geffroy from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/145152/" target="new">Music Note</a> by Creative Stall from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/62502/" target="new">Newspaper</a> by Konrad Michalik from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/541/" target="new">Picture</a> by Edward Boatman from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/19817/" target="new">Poster</a> by irene hoffman from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/36568/" target="new">quill</a> by Mister Pixel from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/18924/" target="new">Speaker</a> by Icomatic from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/1128220/" target="new">vhs</a> by Creaticca Creative Agency from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
            <li><a href="https://thenounproject.com/icon/36452/" target="new">video-support</a> by Vicons Design from <a href="https://thenounproject.com" target="new">the Noun Project</a></li>
        </ul>
        <br />
    </p>
    <p>
        <h3>Cookie Consent Popup</h3>
        <p>
            Der Code für das Cookie Consent Popup "Klaro" kommt von der KIProtect
            GmbH. Dieses Unternehmen stellt den Code frei und Open Source unter der
            <a href="https://opensource.org/licenses/BSD-3-Clause" target="_blank">
            BSD-3 Lizenz</a> (https://opensource.org/licenses/BSD-3-Clause) auf 
            <a href="https://github.com/KIProtect/klaro" target="_blank">GitHub</a>
            (https://github.com/KIProtect/klaro) zur Verfügung. Wir danken vielmals.
        </p>
    <br />
    </p>
    <p>
        <h3>Datumswähler</h3>
        <p>
            Der Code für den Datumswähler (kleines Popup mit der Kalenderauswahl)
            stammt von UX Solutions. Er wurde Open Source unter der Lizenz
            <a href="https://www.apache.org/licenses/LICENSE-2.0" target="_blank">
            Apache License 2.0 Lizenz</a>
            (https://www.apache.org/licenses/LICENSE-2.0) auf 
            <a href="https://github.com/uxsolutions/bootstrap-datepicker"
            target="_blank">GitHub</a>
            (https://github.com/uxsolutions/bootstrap-datepicker) zur Verfügung
            gestellt. Danke dafür!
        </p>
    <br />
    </p>
    <p>
        <h3>Auswertung von AKsearch-Besuchen</h3>
        <p>
            Zur statistischen und DSGVO-konformen Auswertung von AKsearch-Besuchen
            wird die Software "Matomo" eingesetzt. Matomo wird unter der Lizenz
            <a href="https://www.gnu.org/licenses/gpl-3.0.de.html" target="_blank">
            GNU General Public License v3.0</a>
            (https://www.gnu.org/licenses/gpl-3.0.de.html) angeboten.
        </p>
    <br />
    </p>
    <p>
        <h3>Metadaten</h3>
        <p>
            Die Metadaten des <a href="https://doaj.org/" target="_blank">Directory
            of Open Acces Journals (DOAJ)</a> (https://doaj.org/), die in AKsearch
            indexiert sind und somit durchsucht werden können, werden unter der
            <a href="https://creativecommons.org/licenses/by-sa/4.0/"
            target="_blank"> Lizenz CC BY-SA 4.0</a>
            (https://creativecommons.org/licenses/by-sa/4.0/) zur Verfügung gestellt.
            Die Metadaten aus anderen Quellen sind entweder völlig frei verfügbar
            oder werden mit Zustimmung des Rechteinhabers verwendet.</p>
        <br />
    </p>
    <p>
        <h3>Buch Cover Vorschaubilder</h3>
        <p>
            Die Vorschaubilder der Buch Covers erhalten wir von der
            <a href="https://openlibrary.org/" target="_blank">OpenLibrary</a>
            (https://openlibrary.org/) Schnittstelle sowie von der
            <a href="https://books.google.com/" target="_blank">Google Books</a>
            (https://books.google.com/) Schnittstelle.
        </p>
        <br />
    </p>
</div>