<?php
// Set up page title:
$this->headTitle($this->translate('privacy_statement'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li class="active"><a href="' . $this->url('content-page', ['page' => 'privacy']) . '">' . $this->transEsc('privacy_statement') . '</a></li>';
?>

<h2>Datenschutzerklärung</h2>
<div style="margin-left: 20px;">
	Der Schutz Ihrer personenbezogenen Daten ist der AK Bibliothek Wien für
	Sozialwissenschaften (kurz: AK Bibliothek Wien) ein Anliegen. Daher finden Sie hier
	Informationen darüber, welche personenbezogenen Daten in den Systemen der AK
	Bibliothek Wien gespeichert werden. Außerdem erfahren Sie den genauen Zweck und die
	Dauer der Speicherung. Weiters werden Sie über Ihre Rechte informiert und können
	Teile der Datenspeicherung auch ausschalten. Bei Fragen oder sonstigen Anliegen
	können Sie sich gerne mithilfe der weiter unten angegebenen Kontaktdaten an uns
	wenden.
</div>
<br />


<h3>Rechtsgrundlage</h3>
<div style="margin-left: 20px;">
	Die Rechtsgrundlage der Verarbeitung Ihrer personenbezogenen Daten durch die AK
	Bibliothek Wien stellt die freiwillige Überlassung dieser Daten Ihrerseits sowie
	Ihre Einwilligung zu ebendieser Verarbeitung dar.
</div>
<br />


<h3>Welche personenbezogenen Daten werden in den Systemen der AK Bibliothek Wien
	gespeichert?</h3>
<div style="margin-left: 20px;">
	<br />
	<h4>Bibliothekssystem "Alma"</h4>
	<p>
		Die AK Bibliothek Wien verwendet das Bibliothekssystem "Alma"
		von der Firma "ExLibris". Dies ist die Software, in der die
		Mitarbeiterinnen und Mitarbeiter der Bibliothek arbeiten. Dort
		werden beispielsweise die Medien erfasst, Entlehnungen und
		Rückgaben gebucht, Erwerbungsvorgänge getätigt sowie auch
		Nutzerinnen und Nutzer, also Ihre Daten, erfasst. Folgende
		personenbezogene Daten werden in "Alma" gespeichert. Dies gilt
		jedoch nur, wenn Sie an der AK Bibliothek Wien ein
		NutzerInnen-Konto eröffnen:
	</p>
	<ul>
		<li>Name und Titel</li>
		<li>Geschlecht</li>
		<li>Zugehörigkeit zu einer NutzerInnen-Gruppe</li>
		<li>Bevorzugte Sprache</li>
		<li>Geburtsdatum</li>
		<li>Erstell- und Ablaufdatum Ihres NutzerInnen-Kontos</li>
		<li>
			Identifikatoren (z. B. ID-Nummer, Strichcode der Lesekarte,
			usw.)
		</li>
		<li>Post-Adresse(n) (z. B. Wohn- und/oder Arbeitsadresse)</li>
		<li>
			E-Mail-Adresse(n) (z. B. private und/oder geschäftliche
			E-Mail-Adresse)
		</li>
		<li>
			Telefonnummer(n) (z. B. private und/oder geschäftliche
			Telefonnummer)
		</li>
	</ul>
	<p>
		Zusätzlich können folgende personenbezogene Daten gespeichert
		werden:
	</p>
	<ul>
		<li>Ihr Beruf (freiwillige Angabe)</li>
		<li>
			Begründungen für Sperren (z. B. bei lange überfälligen
			Büchern)
		</li>
		<li>
			Nachrichten, die aus "Alma" an Sie gesendet wurden (z. B.
			die Benachrichtigung über bereitgestellte Bücher, Mahnungen,
			usw.)
		</li>
		<li>
			Informationen zu Ausleihen, Rückgaben, Bestellungen und
			Vormerkungen, sofern sie welche tätigen. Die Verknüpfung
			zwischen abgeschlossenen Ausleihvorgängen und Ihrer Person
			werden regelmäßig gelöscht (mind. 1 Mal monatlich). Somit
			ist Ihre Entlehnhistorie im Bibliothekssystem "Alma" auch
			für das Bibliothekspersonal nicht mehr nachvollziehbar.
		</li>
	</ul>
	<br />
	<h4>Suchmaschine "AKsearch"</h4>
	<p>
		Die Suchmaschine "AKsearch" ist eine Software, die die AK
		Bibliothek Wien einsetzt und in der Sie ihre Medien suchen und
		bestellen sowie Ihr Konto verwalten können. "AKsearch"
		kommuniziert über Programmier-Schnittstellen mit "Alma" (s. o.).
		Damit diese Kommunikation möglich ist, müssen einige
		personenbezogene Daten, die in "Alma" gespeichert sind, auch in
		"AKsearch" gespeichert werden. Auch einige andere Funktionen
		hängen davon ab (s. u.). In "AKsearch" werden folgende
		personenbezogene Daten gespeichert, wenn ein Sie ein
		NutzerInnen-Konto eröffnen:
	</p>
	<ul>
		<li>Name</li>
		<li>
			Identifikatoren (z. B. ID-Nummer, Strichcode der Lesekarte,
			usw.)
		</li>
		<li>Passwort (verschlüsselt)</li>
		<li>E-Mail-Adresse</li>
		<li>Erstelldatum Ihres NutzerInnen-Kontos</li>
		<li>Datum Ihres letzten-Logins</li>
		<li>Angabe, ob Sie Ihre Entlehnhistorie speichern wollen</li>
		<li>Angabe, ob ein Einmal-Passwort für Sie hinterlegt ist</li>
		<li>Angabe, ob ein Passwortwechsel nötig ist</li>
	</ul>
	<p>
		Ein E-Mail mit folgenden Daten wird beim Erstellen eines
		NutzerInnen-Kontos an die AK Bibliothek Wien versendet:
	</p>
	<ul>
		<li>Name</li>
		<li>Adresse</li>
		<li>E-Mail-Adresse</li>
		<li>Telefonnummer</li>
		<li>Beruf (freiwillige Angabe)</li>
		<li>Geburtsdatum</li>
		<li>Geschlecht</li>
		<li>Österreichischer Meldezettel</li>
		<li>Strichcode der Lesekarte</li>
		<li>Datum, bis wann Ihr Account gültig ist</li>
		<li>Angabe, ob Sie die Datenverarbeitung akzeptiert haben</li>
		<li>Angabe, ob Sie Ihre Entlehnhistorie speichern wollen</li>
		<li>
			Angabe, ob Sie die Benutzungsordnung der AK Bibliothek Wien
			akzeptiert haben
		</li>
	</ul>
	<p>
		Folgende personenbezogene Daten werden nur auf Ihren
		ausdrücklichen Wunsch bzw. durch Ihr Aktiv-Werden gespeichert.
		Die Speicherung kann nur dann erfolgen, wenn Sie ein
		NutzerInnen-Konto haben:
	</p>
	<ul>
		<li>Ihre Entlehnhistorie</li>
		<li>
			Kommentare und Stichworte (so genannte "Tags"), die Sie zu
			einem Datensatz abgeben können
		</li>
		<li>Favoritenlisten, die Sie selbst anlegen können</li>
		<li>Ihre Suchhistorie, die Sie dauerhaft speichern können</li>
	</ul>
	<p>
		Folgende Daten, die jedoch nicht auf Ihre Person bezogen werden
		können, werden bis zum Schließen des Browsers (in der so
		genannten "Session") in AKsearch gespeichert, auch wenn Sie ohne
		NutzerInnen-Konto recherchieren:
	</p>
	<ul>
		<li>Eine Suchhistorie</li>
	</ul>
	<br />
	<h4>Webanalytik mit Matomo (früher: Piwik)</h4>
	<p>
		Wenn Sie die Suchmaschine "AKsearch" (s. o.) der AK Bibliothek
		Wien besuchen, werden Analyse-Daten von der Webanalytik-Software
		"Matomo" (früher "Piwik") gespeichert. Diese Daten können nicht
		mit Ihrer Person in Verbindung gebracht werden. Wir wollen Sie
		jedoch trotzdem darüber informieren, dass sie gespeichert
		werden:
	</p>
	<ul>
		<li>Die von Ihnen eingegebenen Suchbegriffe.</li>
		<li>
			Informationen zu Seitenaufrufen: Name und URL der Seiten,
			die Sie aufgerufen haben. Die Anzahl Ihrer Seitenbesuche
			sowie deren Zeitpunkt und die Dauer. Die Geschwindigkeit, in
			der die jeweils aufgerufene Seite geladen wurde.
		</li>
		<li>
			Angaben zu Links zu Dateidownloads, auf die Sie geklickt
			haben.
		</li>
		<li>Der Ort, von dem aus Sie zugegriffen haben.</li>
		<li>
			Technische Daten zum Browser und Gerät, von dem aus sie
			zugegriffen haben.
		</li>
		<li>
			Die auf die ersten beiden Stellen anonymisierte IP-Adresse,
			von der aus Sie zugreifen (z. B. wenn Ihre tatsächliche
			IP-Adresse 10.20.30.40 lauten würde, wird tatsächlich nur
			10.20.XX.XX gespeichert).
		</li>
		<li>
			Informationen zu der Quelle im Internet, von der aus Sie auf
			"AKsearch" gefunden haben (z. B. ein Link auf einer gewissen
			Seite im Internet, auf Facebook, etc.) und zu welchen
			externen Seiten Sie von "AKsearch" aus weitergekommen sind
			(z. B. wenn Sie auf einen Link in "AKsearch" klicken, der
			Sie auf eine andere Seite im Internet führt).
		</li>
	</ul>
	<br />
	<a name="cookies"></a>
	<h4>Cookies</h4>
	<p>
		Cookies sind kleine Textdateien, die AKsearch auf Ihrem Computer speichert,
		um diesen wiederzuerkennen oder um gewisse Funktionalitäten anbieten zu
		können. Es gibt technisch notwendige Cookies, ohne die AKsearch nicht korrekt
		funktionieren würde. Das sind vor allem Cookies, die Informationen zur
		Sitzungssteuerung, Sprache und zum Seiten-Layout speichern. Diese Cookies
		werden gelöscht, sobald Sie Ihren Browser schließen. Sie können jedoch nicht
		in den Cookie-Einstellungen deaktivert werden.
		Weiters gibt es funktionale Cookies. Diese sind nötig, um einige der
		Funktionalitäten, die AKsearch anbietet, überhaupt korrekt ausführen zu
		können. Da diese Funktionalitäten nicht zwingend für das generelle
		Funktionieren von AKsearch nötig (jedoch empfohlen) sind, können sie in den
		Cookie-Einstellungen deaktiviert werden.
		Schließlich gibt es Cookies die dafür verantwortlich sind, Statistik-Daten
		der NutzerInnen von AKsearch zu sammeln. Diese Daten helfen uns dabei unsere
		Services stetig verbessern zu können. Natürlich können Sie diese Cookies
		in den Cookie-Einstellungen deaktivieren.
	</p>
	<p>
		<b>Cookie-Einstellungen ändern</b>
		<br />
		Hier können Sie Ihre bereits getroffenen Cookie-Einstellungen ändern:
		&nbsp;
		<a class="btn" onclick="return klaro.show();">Cookie-Einstellungen ändern</a>
	</p>
	<br />
</div>


<h3>Weshalb werden die oben genannten Daten gespeichert?</h3>
<div style="margin-left: 20px;">
	<ul>
		<li>
			Zum Bereitstellen der Bibliotheks-Services der AK Bibliothek
			Wien an Sie. Ohne ein NutzerInnen-Konto, mit dem wir Sie
			identifizieren können, können Sie beispielsweise keine
			Bücher entlehnen oder andere Services, wie die "AK
			Bibliothek digital", nutzen.
		</li>
		<li>
			Den österreichischen Meldezettel benötigen wir, um Ihre Adresse
			zu verifizieren. Damit gewährleisten wir, dass Ihre Angaben im System richtig sind.
		</li>
		<li>
			Zur Kontaktaufnahme im Rahmen Ihrer Bibliotheksnutzung. Dies
			kann beispielsweise die Information über für Sie
			bereitgestellte Bücher oder das Versenden von Mahnungen bei
			überfälligen Entlehnungen sein. Sie werden nur zum Zwecke
			der Bibliotheksnutzung von der AK Bibliothek Wien
			kontaktiert.
		</li>
		<li>
			Zum Steuern von Berechtigungen und Zugangsmodalitäten. Zum
			Beispiel können aus lizenzrechtlichen Gründen manche Inhalte
			der AK Bibliothek Wien nur für gewisse NutzerInnen-Gruppen
			zugänglich sein, für andere jedoch nicht.
		</li>
		<li>
			Um herauszufinden, wie lange ein NutzerInnen-Konto schon
			nicht mehr benutzt wurde. Diese hilft der AK Bibliothek Wien
			beim Identifizieren und Löschen von inaktiven Konten.
		</li>
		<li>
			Zu statistischen Auswertungen: Indem die Nutzung der
			Bibliotheksbestände evaluiert wird, kann nachvollzogen
			werden, welche Inhalte besonders häufig nachgefragt werden.
			Damit kann die AK Bibliothek Wien auf Trends reagieren und
			zusätzliche Medien zu stark nachgefragten Themen anschaffen.
			Die Analyse der eingegebenen Suchbegriffe und der von Ihnen
			besuchten Seiten hilft der AK Bibliothek Wien dabei
			ebenfalls. Die Angabe des Ortes, von dem aus auf "AKsearch"
			zugegriffen wird, ermöglicht es beispielsweise, die Services
			der AK Bibliothek Wien in stark nachgefragten Sprachen
			auszubauen oder auch entsprechende Medien anzuschaffen. Die
			Aufzeichnungen zu Verweildauer auf "AKsearch" gibt Hinweise
			darauf, welche Inhalte besonders interessant sind und daher
			möglicherweise stärker ausgebaut werden sollten, und welche
			weniger interessant sind.
		</li>
		<li>
			Die Daten zu den Endgeräten, mit denen Sie auf "AKsearch"
			zugreifen, erleichtert es der AK Bibliothek Wien
			abzuschätzen, für welche (mobilen) Endgeräte die Services
			ausgebaut werden müssen. So kann z. B. die Anzeige für
			Handy- oder Tablet-Bildschirme optimiert werden. Die Analyse
			von Ladegeschwindigkeiten der Seiten weist auf
			problematische Seiten hin, die zu lange benötigen, um
			geladen zu werden.
		</li>
		<li>
			Das Speichern Ihrer Entlehnhistorie ist zwar möglich,
			erfolgt jedoch nur auf Ihren ausdrücklichen Wunsch. Dies ist
			ein reines Serviceangebot an Sie, damit Sie nachvollziehen
			können, welche Medien Sie bereits von der AK Bibliothek Wien
			entlehnt haben.
		</li>
		<li>
			Das Speichern von Daten in Cookies ist für manche Funktionalitäten der
			Seite erforderlich oder zumindest empfehlenswert. Sie können auf dieser
			Seite jedoch auswählen, welche Cookies sie verwenden wollen.
		</li>
	</ul>
	<p>
		Grundsätzlich gilt: Das Speichern Ihrer personenbezogenen Daten
		ist weder vertraglich noch gesetzlich vorgeschrieben oder für
		einen Vertragsabschluss erforderlich. Ohne die Bereitstellung
		Ihrer Daten können Sie jedoch die meisten Services der
		Bibliothek nicht in Anspruch nehmen.
	</p>
	<br />
</div>

<h3>Von welchen Personengruppen werden Daten gespeichert?</h3>
<div style="margin-left: 20px;">
	<p>
		Die oben erwähnten Daten werden von folgenden Personengruppen
		gespeichert:
	</p>
	<ul>
		<li>
			Personen, die ein NutzerInnen-Konto bei der AK Bibliothek
			Wien eröffnen
		</li>
		<li>
			Personen, die die Suchmaschine "AKsearch" der AK Bibliothek
			Wien im Internet besuchen
		</li>
	</ul>
	<p>
		Die Angabe darüber, welche Daten genau in welchem der beiden
		Fälle gespeichert werden, entnehmen Sie bitte den oberen
		Abschnitten dieser Datenschutzerklärung.
	</p>
	<br />
</div>


<h3>Wie lange werden personenbezogene Daten gespeichert?</h3>
<div style="margin-left: 20px;">
	<p>
		Wie lange die personenbezogenen Daten gespeichert werden hängt
		davon ab, zu welchem Zeitpunkt Sie zuletzt aktiv waren. Die
		Regel der AK Bibliothek Wien lautet: Wenn folgende Umstände
		zutreffen werden alle Ihre personenbezogenen Daten
		unwiderruflich gelöscht:
	</p>
	<ul>
		<li>
			Es sind keine aktiven Entlehnungen oder Bestellungen bzw.
			Vormerkungen auf Ihr BenutzerInnen-Konto in unserem
			Bibliothekssystem "Alma" verbucht.
		</li>
		<li>
			Sie haben sich seit mindestens 2 Jahren nicht mehr in
			"AKsearch" oder der AK Bibliothek digital angemeldet.
		</li>
	</ul>
	<p>
		Die Laufzeit der 2-jährigen Frist beginnt im Jahr des
		Inkrafttretens der Datenschutz-Grundverordnung (2018) und
		bezieht sich auf das Kalenderjahr. Der früheste Löschtermin ist
		somit der 1. Jänner 2021. Aufgrund von Wochenenden, Feiertagen,
		personeller Verfügbarkeit oder technischen Umstände kann sich
		die Löschung eventuell verzögern, wird aber so zeitnah
		wie möglich zum erwähnten Stichtag durchgeführt. Dabei kann als Richtwert ca.
		1 Monat angesehen werden. Die zur Löschung anfallendend Daten werden somit
		also erstmals im Laufe des Jänner 2021 gelöscht. Sollten Sie
		nach der Löschung Ihres Kontos die AK Bibliothek Wien wieder
		nutzen wollen, müssen Sie ein neues Konto eröffnen.
	</p>
	<p>
		Der Meldezettel wird nach Aktivierung Ihres Benutzerkontos von uns gelöscht.
	</p>

	<br />
</div>


<h3>An wen werden personenbezogene Daten übermittelt?</h3>
<div style="margin-left: 20px;">
	<p>
		Das Bibliothekssystem "Alma" ist eine so genannte
		"Cloud-Software". D. h. die Software ist nicht lokal auf den
		Computern der AK Bibliothek Wien installiert, sondern wird über
		das Internet mithilfe eines Browsers bedient. Die Software
		selbst ist auf einem Server in den Niederlanden installiert. An
		diese Server werden die personenbezogenen Daten, die in "Alma"
		verwaltet werden, übermittelt. Die Server werden von der Firma
		"ExLibris" betreut.
	</p>
	<p>
		Die Suchmaschine "AKsearch" sowie die Webanalytik-Software
		"Matomo" (früher "Piwik") laufen auf Servern des Betreibers
		"Anexia" in Österreich. Die Serverbetreuung erfolgt durch die AK
		Bibliothek Wien selbst.
	</p>
	<br />
</div>


<h3>Ihre Rechte</h3>
<div style="margin-left: 20px;">
	<p>
		Wir weisen Sie darauf hin, dass Sie folgende Rechte in Bezug auf
		Ihre bei der AK Bibliothek Wien gespeicherten personenbezogenen
		Daten haben:
	</p>
	<ul>
		<li>
			<strong>Recht auf Auskunft:</strong><br />
			Sie haben das Recht, sich über Ihre bei der AK Bibliothek
			Wien gespeicherten personenbezogenen Daten zu informieren.
		</li>
		<br />
		<li>
			<strong>Recht auf Berichtigung:</strong><br />
			Sofern Ihre bei der AK Bibliothek Wien gespeicherten
			personenbezogenen Daten falsch sind, haben Sie das Recht,
			diese berichtigen zu lassen.
		</li>
		<br />
		<li>
			<strong>Recht auf Löschung:</strong><br />
			Sie haben das Recht, Ihre bei der AK Bibliothek Wien
			gespeicherten personenbezogenen Daten löschen zu lassen.
		</li>
		<br />
		<li>
			<strong>Recht auf Einschränkung:</strong><br />
			Unter gewissen Umständen (siehe
			<a href="http://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32016R0679&from=DE" target="_blank">
				http://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32016R0679&from=DE
			</a>
			, Abschnitt 3, Artikel 18) können Sie eine Einschränkung der
			Verarbeitung Ihrer personenbezogenen Daten anfordern. Die
			betroffenen Daten werden dann zwar weiterhin gespeichert,
			jedoch nicht mehr verarbeitet.
		</li>
		<br />
		<li>
			<strong>Recht auf Widerspruch:</strong><br />
			Sie können einer bereits getroffenen Zustimmung zur
			Verarbeitung Ihrer personenbezogenen Daten widersprechen.
			Sollten Sie dies tun, wird die AK Bibliothek Wien die
			betroffenen Daten löschen, um eine weitere Verarbeitung zu
			verhindern. Die Rechtmäßigkeit der Verarbeitung der
			betroffenen Daten zwischen Ihrer Einwilligung und Ihrem
			Widerspruch bleibt davon unberührt.
		</li>
		<br />
		<li>
			<strong>Recht auf Datenübertragbarkeit:</strong><br />
			Sie haben das Recht, Ihre bei der AK Bibliothek Wien
			gespeicherten personenbezogenen Daten in einem gängigen
			maschinenlesbaren Format (z. B. Excel, XML, CSV, …) zu
			erhalten.
		</li>
		<br />
		<li>
			<strong>Recht auf Beschwerde:</strong><br />
			Wenn Sie vermuten, dass Ihre personenbezogenen Daten
			unrechtmäßig verarbeitet wurden, haben Sie das Recht,
			Beschwerde bei einer Aufsichtsbehörde einzulegen. In
			Österreich ist dies die Datenschutzbehörde.
		</li>
	</ul>
	<br />
</div>


<h3>An wen können Sie sich wenden?</h3>
<div style="margin-left: 20px;">
	<p>
		Wenn Sie Fragen haben, Auskünfte benötigen oder von Ihren
		Rechten Gebrauch machen wollen, wenden Sie sich mit Ihrem
		Anliegen per eMail an:
	</p>
	<p>
		<div style="text-indent: 20px">
			<a href="mailto:<?=$this->escapeHtmlAttr($this->library_email)?>"><?=$this->escapeHtml($this->library_email)?></a>
		</div>
	</p>
	<p>oder postalisch an:</p>
	<p>
		<div style="text-indent: 20px">
			Kammer für Arbeiter und Angestellte für Wien
		</div>
		<div style="text-indent: 20px">
			AK Bibliothek Wien für Sozialwissenschaften
		</div>
		<div style="text-indent: 20px">Prinz-Eugen-Straße 20-22</div>
		<div style="text-indent: 20px">1040 Wien</div>
	</p>
	<p>oder telefonisch an:</p>
	<div style="text-indent: 20px">
		<a href="tel:<?=$this->escapeHtmlAttr($this->library_phone_href)?>"><?=$this->escapeHtml($this->library_phone_display)?></a>
	</div>
	<br />
</div>


<h3>Datenspeicherung einschränken</h3>
<div style="margin-left: 20px;">
	<p>
		Hier können Sie die Speicherung der Daten Ihrer Besuche auf
		"AKsearch", die mithilfe der Webanalytik-Software "Matomo"
		(früher "Piwik") durchgeführt werden, ausschalten. Bitte
		beachten Sie: Wenn Sie die Speicherung deaktivieren wird ein
		Cookie in Ihrem Browser hinterlegt, das verhindert, dass
		Ihre Besuchsdaten an "Matomo" übertragen werden. Sollten Sie
		Ihre Browser Cookies löschen so müssen Sie die Auswertung
		erneut deaktivieren.
	</p>
	<p>
		Zur Information: Sie können das Tracking durch "Matomo" auch mittels
		der Do-Not-Track Einstellung Ihres Browsers oder durch den Einsatz
		eines Ad-Blockers verhindern.
	</p>
	<br />
	<iframe id="matomoOptOut" src="<?=$this->escapeHtmlAttr($this->matomo_url)?>?module=CoreAdminHome&action=optOut&language=de&backgroundColor=ffffff&fontColor=333333&fontSize=14px&fontFamily=%22Helvetica%20Neue%22%2CHelvetica%2CArial%2Csans-serif"></iframe>

</div>