<br />
<div class="form-group">
  <label class="control-label"><?=$this->transEsc('Phone Number')?>:</label>
  <input type="text" name="phone" id="phone" class="form-control" value="<?=$this->userdata['phone']?>" />
</div>

<div class="form-group">
  <label class="control-label"><?=$this->transEsc('Mobile Number')?>:</label>
  <input type="text" name="mobile_phone" id="mobile_phone" class="form-control" value="<?=$this->userdata['mobile_phone']?>" />
</div>

<div class="form-group">
  <label class="control-label"><?=$this->transEsc('Email')?>:</label>
  <input type="text" name="email" id="email" class="form-control" value="<?=$this->userdata['email']?>" />
</div>