<?=$this->translate(
    'new_user_library_email_text',
    [
        '%%barcode%%' => $this->barcode,
        '%%firstname%%' => $this->firstname,
        '%%lastname%%' => $this->lastname,
        '%%street%%' => $this->street,
        '%%zip%%' => $this->zip,
        '%%city%%' => $this->city,
        '%%email%%' => $this->email,
        '%%phone%%' => $this->phone,
        '%%birthday%%' => $this->birthday,
        '%%expiryDate%%' => $this->expiryDate,
        '%%statistics%%' => $this->statistics,
        '%%dataProcessing%%' => $this->dataProcessing,
        '%%loanHistory%%' => $this->loanHistory,
        '%%houseAndUsageRules%%' => $this->houseAndUsageRules,
    ]);
?>